### ISSUE TITLE
Please Provide steps to stream twitter data in kinesis with code because i am new to amazon kinesis

### ISSUE THREAD

**Issue by sheik5azmal** [owickstrom/twitter-kinesis-lab#3]
Please Provide steps to stream twitter data in kinesis with code because i am new to amazon kinesis.

with detail steps

**Comment by owickstrom** [comment]
Hi,

That is basically what the code in this repository does. It might not be in that level of detail, but that should probably be a blog post or something like that.

For more detailed information and tutorials, perhaps in another language than Clojure, you should probably start reading the documentation at http://docs.aws.amazon.com/kinesis/latest/dev/introduction.html.

Hope that helps!
